# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWW5YHcXax7hW_8yTFcrA6jn7rOCVqol
"""

pip install streamlit

import streamlit as st
st.title('My first app')
st.write("hello sandhiya!...")

